# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coords',
            new_name='point',
        ),
    ]
