# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_content',
            field=models.TextField(blank=True, null=True, verbose_name='Content (Translated)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
    ]
