# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 21:13
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('display_name', models.CharField(max_length=50, verbose_name='Display Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('about_me', models.CharField(blank=True, max_length=255, null=True)),
                ('age', core.models.IntegerRangeField(blank=True, null=True)),
                ('height', core.models.IntegerRangeField(blank=True, null=True)),
                ('weight', core.models.IntegerRangeField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('AS', 'Asian'), ('BL', 'Black'), ('LA', 'Latino'), ('ME', 'Middle Eastern'), ('MI', 'Mixed'), ('NA', 'Native American'), ('WH', 'White'), ('SA', 'South Asian'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Ethnicity')),
                ('body_type', models.CharField(blank=True, choices=[('TO', 'Toned'), ('AV', 'Average'), ('LA', 'Large'), ('MU', 'Muscular'), ('SL', 'Slim'), ('ST', 'Stocky')], max_length=2, null=True, verbose_name='Body Type')),
                ('position', models.CharField(blank=True, choices=[('TO', 'Top'), ('VT', 'Vers Top'), ('VS', 'Versatile'), ('VB', 'Vers Bottom'), ('BO', 'Bottom')], max_length=2, null=True, verbose_name='Position')),
                ('rel_status', models.CharField(blank=True, choices=[('CO', 'Committed'), ('DA', 'Dating'), ('EN', 'Engaged'), ('EX', 'Exclusive'), ('MA', 'Married'), ('OR', 'Open Relationship'), ('PA', 'Partnered'), ('SI', 'Single')], max_length=2, null=True, verbose_name='Relationship Status')),
                ('hiv_status', models.CharField(blank=True, choices=[('NE', 'Negative'), ('NP', 'Negative, on PrEP'), ('PO', 'Positive'), ('PU', 'Positive, Undetectable')], max_length=2, null=True, verbose_name='HIV Status')),
                ('hiv_test_date', models.DateField(blank=True, null=True, verbose_name='HIV Test Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5)),
                ('lang_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
