# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.Image')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Image',
                'verbose_name_plural': 'Message Images',
            },
            bases=('images.image',),
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
