# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20170826_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimageorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileImageOrder',
        ),
    ]
