# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170827_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='next_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.ProfileImage', verbose_name='Next Image'),
        ),
    ]
