# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_name',
            field=models.CharField(max_length=100),
        ),
    ]
